### ISSUE TITLE
Unable To Read Data

### ISSUE THREAD

**Issue by Youssef93** [zedlab/hapi-arc-example#1]
- hapiArch.deps.pluginName doesn't read added files inside the plugin

- hapiArch.deps doesn't read other plugins

- This could've happened after yesterday's bug

**Comment by AhmedAli7O1** [comment]
> hapiArch.deps.pluginName doesn't read added files inside the plugin

it works it's just loaded after the module your trying to access it from, e.g you're trying to log it in the controller, but unlike the old version, anything you add will by default load after all other specified modules in the `specification.json` so if you need to access this file/folder in the controller you'll need to specify it in the `specification.json` before controllers
e.g
```json
[
 {
    "name": "newModule.js",
    "type": "module"
 },
  {
    "name": "controllers",
    "type": "component",
    "modules":[
    ]
  }
]
```

> hapiArch.deps doesn't read other plugins

verified it's working and added a second plugin in the example project

**Comment by AhmedAli7O1** [comment]
also allowed `specification.json` for each plugin so now each plugin can have a different structure, e.g pluginOne is `controllers > service > models` pluginTwo is `controllers > models` etc
