### ISSUE TITLE
Transfer inputs/flags in CLI to whatever testing tool used

### ISSUE THREAD

**Issue by Youssef93** [zedlab/hapi-arc-example#2]
example:
 npm test --timeout=3000
should be equivalent to
mocha "filename" --timeout=3000 (if mocha is used as a testing tool)

**Comment by AhmedAli7O1** [comment]
done, tested with `npm test timeout=10000 reporter=list`

notice, no `--` e,g `--timeout=10000` just `timeout=10000`
